/**
 * lib/adaptiveIntervention.ts
 *
 * Adaptive AI Intervention Engine
 * Transforms ML predictions into intelligent, personalized adherence interventions.
 *
 * Architecture:
 * 1. Rule-Based Clinical Safety Layer (preserved boundaries)
 * 2. Feature Extraction & Behavioral Analytics Layer
 * 3. Random Forest Predictive Risk Classification (existing)
 * 4. Adaptive AI Intervention Engine (this file)
 * 5. Personalized Reminder & Predictive Adherence Support Layer
 * 6. Caregiver Escalation & Monitoring Layer
 *
 * Medical references:
 * - WHO Medication Adherence Guidelines (2003)
 * - Morisky Medication Adherence Scale behavioral thresholds
 * - ≥80% adherence = clinical benchmark for hypertension/diabetes
 */

import type { RiskLevel, TrendDirection, AdherenceFeatures } from './adherenceEngine';

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

export type InterventionIntensity = 'minimal' | 'moderate' | 'aggressive';
export type EscalationPriority = 'none' | 'low' | 'medium' | 'high' | 'critical';

/** Behavioral pattern learned from historical intake data */
export interface BehavioralPattern {
  /** Average actual intake delay in minutes (positive = late, negative = early) */
  avgIntakeDelayMinutes: number;
  /** Most common intake delay bucket */
  delayProfile: 'early' | 'ontime' | 'slightly_late' | 'late' | 'very_late';
  /** Hour of day with highest missed-dose probability */
  peakMissHour: number | null;
  /** Whether user tends to cluster missed doses (e.g., always misses afternoon dose) */
  hasClusteredMisses: boolean;
  /** Recent 7-day delay trend vs historical */
  delayTrend: 'improving' | 'stable' | 'worsening';
  /** Consecutive missed dose streak */
  currentMissStreak: number;
  /** Longest historical miss streak */
  maxHistoricalMissStreak: number;
}

/** Adaptive reminder configuration generated by the intervention engine */
export interface AdaptiveReminderConfig {
  /** How many minutes before scheduled time to send the first reminder */
  leadTimeMinutes: number;
  /** Number of reminder follow-ups if no confirmation received */
  followUpCount: number;
  /** Interval between follow-up reminders in minutes */
  followUpIntervalMinutes: number;
  /** Whether to enable escalation notifications */
  escalationEnabled: boolean;
  /** Whether to show motivational/supportive messaging */
  motivationalMessagingEnabled: boolean;
  /** Intervention intensity level */
  intensity: InterventionIntensity;
  /** Caregiver escalation priority */
  escalationPriority: EscalationPriority;
  /** Predictive lead: extra minutes added based on behavioral pattern */
  behavioralLeadTimeBonus: number;
  /** Human-readable explanation of the intervention decision */
  interventionReason: string;
  /** Recommended notification message tone */
  messageTone: 'gentle' | 'neutral' | 'urgent' | 'critical';
  /** Whether system should enter high-sensitivity monitoring mode */
  highSensitivityMode: boolean;
  /** Suggested clinical action (for display / caregiver) */
  clinicalActionSuggestion: string;
}

/** Full intervention analysis output */
export interface AdaptiveInterventionResult {
  /** Behavioral pattern analysis */
  behavioralPattern: BehavioralPattern;
  /** Generated adaptive reminder configuration */
  reminderConfig: AdaptiveReminderConfig;
  /** Intervention summary for UI display */
  interventionSummary: string;
  /** Whether this result represents an escalation from previous level */
  isEscalation: boolean;
  /** Risk level that drove this intervention */
  drivingRiskLevel: RiskLevel;
  /** Confidence in the intervention decision (0-100) */
  interventionConfidence: number;
  /** Key behavioral signals that drove intervention */
  keySignals: string[];
}

/** Raw log entry for behavioral pattern extraction */
export interface RawLogForBehavior {
  status: string;
  scheduledDate: string;
  scheduledTime: string;
  takenAt?: Date | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Clinical Safety Constants (immutable boundaries)
// ─────────────────────────────────────────────────────────────────────────────

const CLINICAL_SAFETY = {
  /** Maximum lead time for reminder (minutes) — never alert too far in advance */
  MAX_LEAD_TIME_MINUTES: 60,
  /** Minimum lead time (minutes) — always give some notice */
  MIN_LEAD_TIME_MINUTES: 10,
  /** Maximum follow-up reminders before escalation */
  MAX_FOLLOWUP_COUNT: 5,
  /** Minimum follow-up interval (minutes) */
  MIN_FOLLOWUP_INTERVAL_MINUTES: 10,
  /** Maximum follow-up interval (minutes) */
  MAX_FOLLOWUP_INTERVAL_MINUTES: 30,
  /** Adherence rate below which high-sensitivity mode activates */
  HIGH_SENSITIVITY_THRESHOLD: 50,
  /** Consecutive misses triggering caregiver escalation */
  CAREGIVER_ESCALATION_MISS_THRESHOLD: 3,
  /** Adherence rate below which caregiver escalation is critical */
  CRITICAL_ESCALATION_THRESHOLD: 40,
} as const;

// ─────────────────────────────────────────────────────────────────────────────
// Layer 2: Behavioral Pattern Extractor
// ─────────────────────────────────────────────────────────────────────────────

function parseTimeToMinutes(timeStr: string): number {
  const ampm = timeStr.match(/^(\d{1,2}):(\d{2})\s*(AM|PM)$/i);
  if (ampm) {
    let h = parseInt(ampm[1]);
    const m = parseInt(ampm[2]);
    if (ampm[3].toUpperCase() === 'PM' && h !== 12) h += 12;
    if (ampm[3].toUpperCase() === 'AM' && h === 12) h = 0;
    return h * 60 + m;
  }
  const plain = timeStr.match(/^(\d{1,2}):(\d{2})$/);
  if (plain) return parseInt(plain[1]) * 60 + parseInt(plain[2]);
  return 0;
}

export function extractBehavioralPattern(
  logs: RawLogForBehavior[],
  features: AdherenceFeatures
): BehavioralPattern {
  const now = new Date();

  // Filter to taken logs with timestamps
  const takenWithDelay = logs
    .filter(l => l.status === 'taken' && l.takenAt)
    .map(l => {
      const scheduledMins = parseTimeToMinutes(l.scheduledTime);
      const scheduledDT = new Date(`${l.scheduledDate}T00:00:00`);
      scheduledDT.setMinutes(scheduledDT.getMinutes() + scheduledMins);
      const delayMins = Math.round(
        (new Date(l.takenAt!).getTime() - scheduledDT.getTime()) / 60_000
      );
      return { delay: delayMins, scheduledHour: scheduledDT.getHours() };
    });

  // Average intake delay
  const avgIntakeDelayMinutes =
    takenWithDelay.length > 0
      ? Math.round(
          takenWithDelay.reduce((a, b) => a + b.delay, 0) / takenWithDelay.length
        )
      : 0;

  // Delay profile classification
  let delayProfile: BehavioralPattern['delayProfile'];
  if (avgIntakeDelayMinutes < -5) delayProfile = 'early';
  else if (avgIntakeDelayMinutes <= 10) delayProfile = 'ontime';
  else if (avgIntakeDelayMinutes <= 30) delayProfile = 'slightly_late';
  else if (avgIntakeDelayMinutes <= 60) delayProfile = 'late';
  else delayProfile = 'very_late';

  // Find peak miss hour
  const missedLogs = logs.filter(l => {
    const scheduledMins = parseTimeToMinutes(l.scheduledTime);
    const scheduledDT = new Date(`${l.scheduledDate}T00:00:00`);
    scheduledDT.setMinutes(scheduledDT.getMinutes() + scheduledMins);
    const elapsed = (now.getTime() - scheduledDT.getTime()) / 60_000;
    return l.status !== 'taken' && elapsed > 120;
  });

  const missHours = missedLogs.map(l => {
    const m = parseTimeToMinutes(l.scheduledTime);
    return Math.floor(m / 60);
  });

  let peakMissHour: number | null = null;
  if (missHours.length > 0) {
    const hourCounts: Record<number, number> = {};
    for (const h of missHours) {
      hourCounts[h] = (hourCounts[h] || 0) + 1;
    }
    peakMissHour = parseInt(
      Object.entries(hourCounts).sort((a, b) => b[1] - a[1])[0]?.[0] ?? '0'
    );
  }

  // Clustered miss detection (same scheduled time repeatedly missed)
  const missTimeSlots = missedLogs.map(l => l.scheduledTime);
  const slotCounts: Record<string, number> = {};
  for (const t of missTimeSlots) {
    slotCounts[t] = (slotCounts[t] || 0) + 1;
  }
  const hasClusteredMisses = Object.values(slotCounts).some(c => c >= 3);

  // Delay trend: compare recent 7 days avg delay vs historical
  const sevenDaysAgo = new Date(now);
  sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);
  const recentDateStr = sevenDaysAgo.toISOString().split('T')[0];

  const recentTaken = takenWithDelay.slice(0, 7);
  const olderTaken = takenWithDelay.slice(7);

  const recentAvg =
    recentTaken.length > 0
      ? recentTaken.reduce((a, b) => a + b.delay, 0) / recentTaken.length
      : avgIntakeDelayMinutes;

  const olderAvg =
    olderTaken.length > 0
      ? olderTaken.reduce((a, b) => a + b.delay, 0) / olderTaken.length
      : recentAvg;

  let delayTrend: BehavioralPattern['delayTrend'];
  if (recentAvg < olderAvg - 5) delayTrend = 'improving';
  else if (recentAvg > olderAvg + 5) delayTrend = 'worsening';
  else delayTrend = 'stable';

  // Max historical miss streak
  let maxStreak = 0;
  let streak = 0;
  const sortedLogs = [...logs].sort((a, b) =>
    a.scheduledDate.localeCompare(b.scheduledDate) ||
    parseTimeToMinutes(a.scheduledTime) - parseTimeToMinutes(b.scheduledTime)
  );
  for (const l of sortedLogs) {
    const scheduledMins = parseTimeToMinutes(l.scheduledTime);
    const scheduledDT = new Date(`${l.scheduledDate}T00:00:00`);
    scheduledDT.setMinutes(scheduledDT.getMinutes() + scheduledMins);
    const elapsed = (now.getTime() - scheduledDT.getTime()) / 60_000;
    const isMissed = l.status !== 'taken' && elapsed > 120;
    if (isMissed) {
      streak++;
      maxStreak = Math.max(maxStreak, streak);
    } else {
      streak = 0;
    }
  }

  return {
    avgIntakeDelayMinutes,
    delayProfile,
    peakMissHour,
    hasClusteredMisses,
    delayTrend,
    currentMissStreak: features.consecutiveMissed,
    maxHistoricalMissStreak: maxStreak,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Layer 4: Adaptive AI Intervention Engine
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generates personalized adaptive lead time based on behavioral patterns.
 * Clinical boundary: [MIN_LEAD_TIME, MAX_LEAD_TIME]
 */
function computeAdaptiveLeadTime(
  baseLeadTime: number,
  pattern: BehavioralPattern,
  riskLevel: RiskLevel
): { leadTime: number; bonus: number } {
  let bonus = 0;

  // Add bonus for consistent late intake behavior
  if (pattern.delayProfile === 'slightly_late') bonus += 10;
  if (pattern.delayProfile === 'late') bonus += 20;
  if (pattern.delayProfile === 'very_late') bonus += 30;

  // Add bonus for worsening delay trend
  if (pattern.delayTrend === 'worsening') bonus += 10;

  // Add bonus for clustered misses (predictive prevention)
  if (pattern.hasClusteredMisses) bonus += 10;

  // Add bonus for active miss streak
  if (pattern.currentMissStreak >= 2) bonus += 15;
  if (pattern.currentMissStreak >= 3) bonus += 10;

  // Cap bonus by risk level
  if (riskLevel === 'Low') bonus = Math.min(bonus, 5);
  else if (riskLevel === 'Moderate') bonus = Math.min(bonus, 20);
  // High: allow full bonus

  const rawLeadTime = baseLeadTime + bonus;
  const clampedLeadTime = Math.min(
    CLINICAL_SAFETY.MAX_LEAD_TIME_MINUTES,
    Math.max(CLINICAL_SAFETY.MIN_LEAD_TIME_MINUTES, rawLeadTime)
  );

  return { leadTime: clampedLeadTime, bonus };
}

/**
 * Determines escalation priority based on clinical signals.
 * Uses deterministic boundaries for patient safety.
 */
function computeEscalationPriority(
  features: AdherenceFeatures,
  riskLevel: RiskLevel,
  pattern: BehavioralPattern
): EscalationPriority {
  // Critical: adherence critically low + persistent misses
  if (
    features.adherenceRate < CLINICAL_SAFETY.CRITICAL_ESCALATION_THRESHOLD ||
    pattern.currentMissStreak >= 5
  ) {
    return 'critical';
  }

  // High: multiple clinical signals converge
  if (
    riskLevel === 'High' &&
    pattern.currentMissStreak >= CLINICAL_SAFETY.CAREGIVER_ESCALATION_MISS_THRESHOLD
  ) {
    return 'high';
  }

  // Medium: moderate risk with worsening trend
  if (
    riskLevel === 'High' ||
    (riskLevel === 'Moderate' && pattern.delayTrend === 'worsening')
  ) {
    return 'medium';
  }

  // Low: early-stage moderate concern
  if (riskLevel === 'Moderate' && features.consecutiveMissed >= 2) {
    return 'low';
  }

  return 'none';
}

/**
 * Core adaptive intervention engine.
 * Produces personalized intervention configuration from ML + behavioral signals.
 */
export function generateAdaptiveIntervention(
  features: AdherenceFeatures,
  riskLevel: RiskLevel,
  mlConfidence: number,
  pattern: BehavioralPattern
): AdaptiveReminderConfig {
  let intensity: InterventionIntensity;
  let baseLeadTime: number;
  let followUpCount: number;
  let followUpInterval: number;
  let messageTone: AdaptiveReminderConfig['messageTone'];
  let motivational: boolean;
  let highSensitivity: boolean;
  let interventionReason: string;
  let clinicalAction: string;

  // ── Layer 1: Rule-Based Clinical Safety Boundaries ────────────────────────
  // Base intervention intensity from deterministic risk level
  if (riskLevel === 'Low') {
    intensity = 'minimal';
    baseLeadTime = 30; // standard 30-min reminder
    followUpCount = 1;
    followUpInterval = 20;
    messageTone = 'gentle';
    motivational = false;
    highSensitivity = false;
    interventionReason = 'Adherence is within clinical targets. Standard reminder protocol active.';
    clinicalAction = 'Continue current medication routine. No clinical action required.';
  } else if (riskLevel === 'Moderate') {
    intensity = 'moderate';
    baseLeadTime = 35;
    followUpCount = 2;
    followUpInterval = 15;
    messageTone = 'neutral';
    motivational = true;
    highSensitivity = false;
    interventionReason = 'Moderate adherence risk detected. Elevated reminder protocol activated.';
    clinicalAction = 'Consider reviewing medication routine with healthcare provider at next appointment.';
  } else {
    // High
    intensity = 'aggressive';
    baseLeadTime = 45;
    followUpCount = 4;
    followUpInterval = 10;
    messageTone = 'urgent';
    motivational = true;
    highSensitivity = true;
    interventionReason = 'High adherence risk detected. Aggressive intervention protocol activated.';
    clinicalAction = 'Urgent: consult healthcare provider. Persistent missed doses may impact clinical outcomes for hypertension/diabetes.';
  }

  // ── Layer 4: ML-Driven Behavioral Refinement ──────────────────────────────
  // Refine beyond base rule with behavioral signals

  // Escalate follow-up if consecutive misses detected
  if (features.consecutiveMissed >= 2 && intensity !== 'aggressive') {
    followUpCount = Math.min(followUpCount + 1, CLINICAL_SAFETY.MAX_FOLLOWUP_COUNT);
    followUpInterval = Math.max(
      followUpInterval - 5,
      CLINICAL_SAFETY.MIN_FOLLOWUP_INTERVAL_MINUTES
    );
  }

  // Escalate tone if declining trend
  if (features.trend === 'declining') {
    if (messageTone === 'gentle') messageTone = 'neutral';
    else if (messageTone === 'neutral') messageTone = 'urgent';
  }

  // Activate high sensitivity if recent rate is critically low
  if (features.recentAdherenceRate < CLINICAL_SAFETY.HIGH_SENSITIVITY_THRESHOLD) {
    highSensitivity = true;
    followUpCount = Math.min(followUpCount + 1, CLINICAL_SAFETY.MAX_FOLLOWUP_COUNT);
  }

  // Enable motivational if trend is improving (positive reinforcement)
  if (features.trend === 'improving') {
    motivational = true;
  }

  // Critical threshold: force critical tone
  if (features.adherenceRate < CLINICAL_SAFETY.CRITICAL_ESCALATION_THRESHOLD) {
    messageTone = 'critical';
    highSensitivity = true;
    followUpCount = CLINICAL_SAFETY.MAX_FOLLOWUP_COUNT;
  }

  // ── Layer 5: Behavioral Pattern-Based Lead Time Adjustment ────────────────
  const { leadTime, bonus } = computeAdaptiveLeadTime(baseLeadTime, pattern, riskLevel);

  // ── Layer 6: Caregiver Escalation ─────────────────────────────────────────
  const escalationPriority = computeEscalationPriority(features, riskLevel, pattern);
  const escalationEnabled = escalationPriority !== 'none';

  // Apply clinical safety clamping to all values
  const safeFollowUpCount = Math.min(
    followUpCount,
    CLINICAL_SAFETY.MAX_FOLLOWUP_COUNT
  );
  const safeInterval = Math.max(
    Math.min(followUpInterval, CLINICAL_SAFETY.MAX_FOLLOWUP_INTERVAL_MINUTES),
    CLINICAL_SAFETY.MIN_FOLLOWUP_INTERVAL_MINUTES
  );

  return {
    leadTimeMinutes: leadTime,
    followUpCount: safeFollowUpCount,
    followUpIntervalMinutes: safeInterval,
    escalationEnabled,
    motivationalMessagingEnabled: motivational,
    intensity,
    escalationPriority,
    behavioralLeadTimeBonus: bonus,
    interventionReason,
    messageTone,
    highSensitivityMode: highSensitivity,
    clinicalActionSuggestion: clinicalAction,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Main Adaptive Intervention Analyzer
// ─────────────────────────────────────────────────────────────────────────────

export function analyzeAdaptiveIntervention(
  logs: RawLogForBehavior[],
  features: AdherenceFeatures,
  riskLevel: RiskLevel,
  mlRiskLevel: RiskLevel,
  mlConfidence: number,
  previousRiskLevel?: RiskLevel
): AdaptiveInterventionResult {
  // Extract behavioral pattern (Layer 2)
  const behavioralPattern = extractBehavioralPattern(logs, features);

  // Determine final driving risk (conservative — take higher)
  const riskRank: Record<RiskLevel, number> = { Low: 0, Moderate: 1, High: 2 };
  const drivingRisk: RiskLevel =
    riskRank[riskLevel] >= riskRank[mlRiskLevel] ? riskLevel : mlRiskLevel;

  // Generate adaptive intervention config (Layers 4–6)
  const reminderConfig = generateAdaptiveIntervention(
    features,
    drivingRisk,
    mlConfidence,
    behavioralPattern
  );

  // Detect escalation from previous level
  const isEscalation =
    previousRiskLevel !== undefined &&
    riskRank[drivingRisk] > riskRank[previousRiskLevel];

  // Compute intervention confidence
  // Based on data availability and ML confidence
  const dataConfidence = Math.min(features.totalDue / 10, 1.0); // More data = more confident
  const interventionConfidence = Math.round(
    (mlConfidence * 0.6 + dataConfidence * 100 * 0.4)
  );

  // Build key signals list
  const keySignals: string[] = [];
  if (features.consecutiveMissed >= 2)
    keySignals.push(`${features.consecutiveMissed} consecutive missed doses`);
  if (features.trend === 'declining')
    keySignals.push('Adherence trending downward in recent 7 days');
  if (features.recentAdherenceRate < 60)
    keySignals.push(`Recent 7-day adherence critically low (${features.recentAdherenceRate}%)`);
  if (behavioralPattern.delayProfile === 'late' || behavioralPattern.delayProfile === 'very_late')
    keySignals.push(`Consistent late intake pattern (avg ${behavioralPattern.avgIntakeDelayMinutes} min delay)`);
  if (behavioralPattern.hasClusteredMisses)
    keySignals.push('Repeated missed doses at specific scheduled times detected');
  if (features.adherenceRate < 50)
    keySignals.push(`Overall adherence critically low (${features.adherenceRate}%)`);
  if (features.avgDelayMinutes > 60)
    keySignals.push(`High average dose delay (${features.avgDelayMinutes} min)`);
  if (behavioralPattern.delayTrend === 'worsening')
    keySignals.push('Dose delay behavior worsening over time');
  if (isEscalation)
    keySignals.push(`Escalated from ${previousRiskLevel} to ${drivingRisk} risk`);

  // Build human-readable summary
  let summary = '';
  if (drivingRisk === 'Low') {
    summary =
      'Adherence is stable and within clinical targets. Standard reminder protocol is active. ' +
      (features.trend === 'improving'
        ? 'Your adherence has been improving — keep it up!'
        : 'Maintain your current routine for optimal outcomes.');
  } else if (drivingRisk === 'Moderate') {
    summary =
      `Moderate adherence concern detected (${features.adherenceRate}% rate). ` +
      `Reminders have been adjusted to ${reminderConfig.leadTimeMinutes} minutes before scheduled dose time. ` +
      (reminderConfig.behavioralLeadTimeBonus > 0
        ? `An extra ${reminderConfig.behavioralLeadTimeBonus} minutes has been added based on your intake patterns. `
        : '') +
      'Motivational support notifications are active.';
  } else {
    summary =
      `High adherence risk identified (${features.adherenceRate}% rate, ${features.consecutiveMissed} consecutive miss(es)). ` +
      `Aggressive intervention protocol active: reminders sent ${reminderConfig.leadTimeMinutes} minutes in advance ` +
      `with ${reminderConfig.followUpCount} follow-ups every ${reminderConfig.followUpIntervalMinutes} minutes. ` +
      (reminderConfig.escalationEnabled
        ? `Caregiver escalation is ${reminderConfig.escalationPriority} priority. `
        : '') +
      reminderConfig.clinicalActionSuggestion;
  }

  return {
    behavioralPattern,
    reminderConfig,
    interventionSummary: summary,
    isEscalation,
    drivingRiskLevel: drivingRisk,
    interventionConfidence: Math.min(interventionConfidence, 100),
    keySignals,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Motivational Message Generator (Layer 5)
// ─────────────────────────────────────────────────────────────────────────────

export function generateMotivationalMessage(
  riskLevel: RiskLevel,
  trend: TrendDirection,
  adherenceRate: number,
  medicineName?: string
): string {
  const med = medicineName ? `your ${medicineName}` : 'your medication';

  if (riskLevel === 'Low' && trend === 'improving') {
    return `Great work! Your adherence is improving. Taking ${med} consistently is key to managing your condition effectively.`;
  }
  if (riskLevel === 'Low') {
    return `You're doing well! Keep taking ${med} as scheduled to maintain healthy outcomes.`;
  }
  if (riskLevel === 'Moderate' && trend === 'improving') {
    return `Good progress! Your adherence is getting better. Stay consistent with ${med} — it makes a real difference for your health.`;
  }
  if (riskLevel === 'Moderate') {
    return `Consistency matters. Taking ${med} on time helps keep your condition under control. You can do this — small improvements add up.`;
  }
  if (riskLevel === 'High' && adherenceRate < 50) {
    return `Your health is important. Please take ${med} now — skipping doses for hypertension or diabetes can have serious health consequences. If you're having difficulty, talk to your doctor.`;
  }
  return `Please take ${med} as prescribed. Your healthcare team is counting on your consistent adherence for the best outcomes.`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Escalation Message Generator (Layer 6)
// ─────────────────────────────────────────────────────────────────────────────

export function generateEscalationMessage(
  priority: EscalationPriority,
  features: AdherenceFeatures,
  patientName?: string
): string {
  const name = patientName || 'Patient';
  switch (priority) {
    case 'critical':
      return `CRITICAL ALERT: ${name} has missed ${features.consecutiveMissed} consecutive doses and has an adherence rate of ${features.adherenceRate}%. Immediate follow-up is strongly recommended.`;
    case 'high':
      return `HIGH PRIORITY: ${name}'s medication adherence has dropped to ${features.adherenceRate}% with ${features.consecutiveMissed} missed doses. Please check in with the patient.`;
    case 'medium':
      return `MODERATE CONCERN: ${name}'s adherence is at ${features.adherenceRate}% with a declining trend. Consider reaching out to support adherence.`;
    case 'low':
      return `EARLY WARNING: ${name}'s adherence pattern shows some irregularity (${features.adherenceRate}%). Monitoring has been increased.`;
    default:
      return '';
  }
}